name: pre-commit

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install ruff
        run: pip install ruff
      - name: Get pre-commit
        uses: pre-commit/action@v3.0.0
      - name: Run pre-commit
        run: pre-commit run --all-files
